export const SET_TOKEN = 'set_token'
export const CLEAR_TOKEN = 'clear_token'
export const USER_LOGIN = 'user_login'
export const UPDATE_SCREEN_WIDTH = 'update_screen_width'
export const UPDATE_IS_MOBILE = 'update_is_mobile'
export const UPDATE_TOGGLE_TYPE = 'update_toggle_type'